// import moment from 'moment';

// const days = ['Today', 'Tomorrow', moment().add(1, 'days').format('ddd, MMM D')];

export const qoutes = [
    {
        title: 'Be yourself; everyone else is already taken.',
        poster: 'https://cdn3.volusion.com/zausr.eprhq/v/vspfiles/photos/7072-2.jpg?1468578805',
        tags: 'Inspirational',
        author: 'Oscar Wilde',
        // days,
    },
    {
        title: 'Be the change that you wish to see in the world.',
        poster: 'http://i.ebayimg.com/images/g/sSgAAOSwxH1UGG0b/s-l1600.jpg',
        tags: 'action',
        author: 'Mahatma Gandhi',
        // days,
    },
    {
        title: 'Good friends, good books, and a sleepy conscience: this is the ideal life.',
        poster: 'http://sadmoment.com/wp-content/uploads/2013/08/Inspiring-Mark-Twain-Quote-On-Good-Friends-Books-a-Sleepy-Conscience-The-Ideal-Life.jpg',
        tags: 'Inspirational',
        author: 'Mark Twain',
        // days,
    },
    {
        title: 'I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.',
        poster: 'http://www.inblix.com/images/i-like-nonsense-it-wakes-up-brain-cells-fantasy-necessary-ingredient-living-dr-seuss.jpg',
        tags: 'fantasy',
        author: 'Dr. Seuss',
        // days,
    },
    {
        title: 'If you judge people, you have no time to love them.',
        poster: 'http://www.azquotes.com/picture-quotes/quote-if-you-judge-people-you-have-no-time-to-love-them-mother-teresa-34-42-53.jpg',
        tags: 'life',
        author: 'Mother Teresa',
        // days,
    },
    {
        title: 'Logic will get you from A to Z; imagination will get you everywhere.',
        poster: 'http://www.dawn-productions.com/core/wp-content/uploads/2013/01/Einstein_Logic-will-get-you-from-A-to-B-640x4471.png',
        tags: 'imagination',
        author: 'Albert Einstein',
        // days,
    },
    {
        title: 'One good thing about music, when it hits you, you feel no pain.',
        poster: 'https://pics.me.me/one-good-thing-about-music-when-it-hits-you-you-11512515.png',
        tags: 'music',
        author: 'Bob Marley',
        // days,
    },
    {
        title: 'Folks are usually about as happy as they make their minds up to be.',
        poster: 'http://izquotes.com/quotes-pictures/quote-folks-are-usually-about-as-happy-as-they-make-their-minds-up-to-be-abraham-lincoln-112680.jpg',
        tags: 'happiness',
        author: 'Abraham Lincoln',
        // days,
    },
    {
        title: 'It’s no use going back to yesterday, because I was a different person then.',
        poster: 'http://spiritualcleansing.org/wp-content/uploads/2015/08/It%E2%80%99s-no-use-going-back-to-yesterday-because-I-was-a-different-person-then..jpg',
        tags: 'philosophy',
        author:'Lewis Carroll',
        // days,
    },
    {
        title: 'Books are a uniquely portable magic.',
        poster: 'http://spiritualcleansing.org/wp-content/uploads/2015/09/Books-are-a-uniquely-portable-magic..jpg',
        tags: 'magic',
        author: 'Stephen King',
        // days,
    },

    {
        title: 'A day without laughter is a day wasted.',
        poster: 'http://spiritualcleansing.org/wp-content/uploads/2015/08/A-day-without-laughter-is-a-day-wasted..jpg',
        tags: 'philosophy',
        author: 'Nicolas Chamfort',
        // days,
    },
    {
        title: 'Knowing yourself is the beginning of all wisdom.',
        poster: 'http://emilysquotes.com/wp-content/uploads/2015/09/Knowing-yourself-is-the-beginning-of-all-wisdom..jpg',
        tags: 'introspection',
        author: 'Aristotle',
        // days,
    },
    {
        title: 'It is the possibility of having a dream come true that makes life interesting.',
        poster: 'https://i.pinimg.com/736x/69/84/6f/69846fa728b83c9cfd272325fe6b2889--dream-come-true-a-dream.jpg',
        tags: 'inspirational',
        author: 'Paulo Coelho',
        // days,
    },
    {
        title: 'The only true wisdom is in knowing you know nothing.',
        poster: 'http://www.azquotes.com/picture-quotes/quote-the-only-true-wisdom-is-in-knowing-you-know-nothing-socrates-66-71-57.jpg',
        tags: 'wisdom',
        author: 'Socrates',
        // days,
    },
    {
        title: 'Do what you feel in your heart to be right – for you’ll be criticized anyway.',
        poster: 'http://izquotes.com/quotes-pictures/quote-do-what-you-feel-in-your-heart-to-be-right-for-you-ll-be-criticized-anyway-you-ll-be-damned-if-eleanor-roosevelt-262760.jpg',
        tags: 'inspirational',
        author: 'Eleanor Roosevelt',
        // days,
    },
    {
        title: 'We love the things we love for what they are.',
        poster: 'http://izquotes.com/quotes-pictures/quote-we-love-the-things-we-love-for-what-they-are-robert-frost-230296.jpg',
        tags: 'love',
        author: 'Robert Frost',
        // days,
    },
    {
        title: 'Happiness is not something ready made. It comes from your own actions.',
        poster: 'http://thequotes.in/wp-content/uploads/2016/01/DALAI-LAMA-quotes-6-1024x460.jpg',
        tags: 'happiness',
        author: 'Dalai Lama XIV',
        // days,
    },
    {
        title: 'A Penny Saved is a Penny Earned.',
        poster: 'http://izquotes.com/quotes-pictures/quote-a-penny-saved-is-a-penny-earned-benjamin-franklin-65291.jpg',
        tags: 'money',
        auther: 'Benjamin Franklin',
        // days,
    },
    {
        title: 'Education is the most powerful weapon which you can use to change the world.',
        poster: 'http://spiritualcleansing.org/wp-content/uploads/2016/01/Education-is-the-most-powerful-weapon-which-you-can-use-to-change-the-world..jpg',
        tags: 'education',
        author: 'Nelson Mandela',
        // days,
    },
    {
        title: 'It does not matter how slowly you go as long as you do not stop.',
        poster: 'http://motivationalreads.com/wp-content/uploads/it-doesnt-matter-how-slowly-you-go-as-long-as-you-do-not-stop.jpg',
        tags: 'perseverance',
        author: 'Confucius',
        // days,
    },
    {
        title: 'Love all, trust a few, do wrong to none.',
        poster: 'https://i2.wp.com/www.inspirationinpictures.com/wp-content/uploads/2013/12/130705-3.jpg?w=550',
        tags: 'love',
        author: 'William Shakespeare',
        // days,
    },
    {
        title: 'There is nothing in the world so irresistibly contagious as laughter and good humor.',
        poster: 'http://www.azquotes.com/picture-quotes/quote-there-is-nothing-in-the-world-so-irresistibly-contagious-as-laughter-and-good-humor-charles-dickens-37-45-71.jpg',
        tags: 'humor',
        author: 'Charles Dickens',
        // days,
    },
    {
        title: 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.',
        poster: 'https://www.askideas.com/media/12/Darkness-cannot-drive-out-darkness-only-light-can-do-that.-Hate-cannot-drive-out-hate-only-love-can-do-that.-9.jpg',
        tags: '',
        author: 'Martin Luther King, JR.',
        // days,
    },
    {
        title: 'Life is what happens to us while we are making other plans.',
        poster: 'http://www.appreciationsociety.com/wp-content/uploads/2016/06/June-23-Allen-Saunders.png',
        tags: 'life',
        author: 'Allen Saunders',
        // days,
    },
    {
        title: 'It is never too late to be what you might have been.',
        poster: 'https://www.great-quotes.com/static/managed_images/AC/AC2FE7AA-88B7-11E1-90C9-A0DE42EEE2F5.jpg',
        tags: 'inspirational',
        author: 'George Eliot',
        // days,
    },
    {
        title: 'There is no greater agony than bearing an untold story inside you.',
        poster: 'http://www.orthodoxandgay.com/wp-content/uploads/2015/06/Maya-Angelou.png',
        tags: 'inspirational',
        author: 'Maya Angelou',
        // days,
    },
    {
        title: 'When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.',
        poster: 'http://www.azquotes.com/picture-quotes/quote-when-one-door-of-happiness-closes-another-opens-but-often-we-look-so-long-in-disappointment-helen-keller-78-77-16.jpg',
        tags: 'inspirational',
        author: 'Helen Keller',
        // days,
    },
    {
        title: 'In a conflict between the heart and the brain, follow your heart. ',
        poster: 'https://i.pinimg.com/736x/52/a8/2a/52a82a6e3ec8affd6f109b5004c2bab0--swami-vivekananda-quotes-soul-quotes.jpg',
        tags: 'motivational',
        author:'Swami Vivekananda',
        // days,
    },
    {
        title: 'An eye for an eye will only make the whole world blind.',
        poster: 'http://quotespictures.com/wp-content/uploads/2013/03/an-eye-for-for-eye-only-ends-up-making-the-whole-world-blind.jpg',
        tags: 'peace',
        author: 'Mahatma Gandhi',
        // days,
    },
    {
        title: 'Count your age by friends, not years. Count your life by smiles, not tears.',
        poster: 'http://statusmind.com/images/2015/01/Smart-Quotes-54453-statusmind.com.jpg',
        tags: 'timelessness',
        author: 'John Lennon',
        // days,
    },
    {
        title: 'The greatest religion is to be true to your own nature. Have faith in yourselves.',
        poster: 'http://atmanirvana.com/wp-content/uploads/2016/11/Swami-Vivekananda-Quote-5.jpg',
        tags: 'faith',
        author: 'Swami Vivekanand',
        // days,
    },
];